### ISSUE TITLE
 cannot import name patterns django 1.10.7 Mezzanine 4.2.3

### ISSUE THREAD

**Issue by bigoss** [jpells/mezzanine-agenda#10]
Adding to urls.py as described in installation getting

site-packages\mezzanine_agenda\urls.py", line 3, in <module>
    from django.conf.urls import patterns, url
ImportError: cannot import name patterns

**Comment by ephsmith** [comment]
This is just a symptom of stalled development.  

Per the [Django documentation](https://docs.djangoproject.com/en/1.9/ref/urls/#patterns):

> django.conf.urls utility functions
>
>patterns()
>
>patterns(prefix, pattern_description, ...)[source]
>Deprecated since version 1.8:
>urlpatterns should be a plain list of django.conf.urls.url() instances instead.

Looks like an easy fix.
