### ISSUE TITLE
Events not showing in page

### ISSUE THREAD

**Issue by MelvinDRM** [jpells/mezzanine-agenda#3]
Hello,

I'm new to Django (therefore Mezzanine) and I'm working on a site where I would like to use this app for events due to its approach of custom content type (more organised).

I installed following the instructions and although I faced a problem with the sentence: *Add `("^%s/" settings.EVENT_SLUG, include("mezzanine_agenda.urls")),` to your `urls.py`* (it said that there was a Syntax error), I changed it to *`("^events/", include("mezzanine_agenda.urls")),`* and all good.

After migrating the database and running the server, I created the Events page, and created a couple of events, and nothing is showing in the page (just the Suscribre to all events button). Oddly, the breadcrumb section does in fact shows that there are events, and of course you can access them directly.

The only user I have is the superuser one, and just to be sure I explicitely assigned all permissions just in case.

Any ideas?

Thanks in advance

MDRM

**Comment by MelvinDRM** [comment]
Well, I figured out the "problem". The thing is that in the `views.py`, line 62, there is a filter to show the events from the actual time and forward. My intention is to keep and show the record of past events, and this doesn't help me do that.

My solution was to simply comment that line, which means that I changed this...:

```javascript
#... 

60    if not tag and not year and not location and not username:
61        #Get upcoming events/ongoing events
62        events = events.filter(Q(start__gt=datetime.now()) | Q(end__gt=datetime.now())).order_by("start")

#...
```

... to this...:

```javascript
#... 

60    if not tag and not year and not location and not username:
61        #Get upcoming events/ongoing events
62        # events = events.filter(Q(start__gt=datetime.now()) | Q(end__gt=datetime.now())).order_by("start")
63        pass

#...
```

And that's it. So far it doesn't break the app. I'll let you know if there is any trouble. In the meantime, if you have a better solution, let me know.

MDRM

**Comment by jpells** [comment]
Correct! This app was intended to show upcoming events and past events would be viewable from the archive. Commenting out that line shows all events.
